spring:
  application:
    name: qlik-test
server:
  port: 8080


# All endpoints are enabled.
management:
  endpoints:
    web:
      exposure:
        include: health,info,logfile,metrics,loggers,readiness
  endpoint:
    health:
      show-details: always

amazon:
  dynamodb:
    embedded: false
  aws:
    accessKey: key
    secretKey: key2


# Swagger
swagger:
  service:
    version: "1.0"
    title: ${spring.application.name}
    description: "A service that provides APIs for ..."
    termsPath: ""
    licenceType: ""
    licencePath: ""